### PR TITLE
Revert react integration to tracking current dispatcher

### LINKED ISSUE #251: Using signals package with react router results in a wierd jsx error
I tried using `@preact/signals-react` in a project with react-router 6 but I got that error which doesn't make any sense to me, the error is complaining about react-router but originates from `@preact/signals-react` and only happens when I import/use anything from `@preact/signals-react`

image

here is a link https://stackblitz.com/edit/react-router-starter-gfxkdm?file=components%2FHome.js  to reproduce the error, try commenting out the signal import/usage in Home.js and everything will work fine 

I think it could be related to the patches to JSX factories, which breaks the react-router check for the `<Route/>`  element type somehow, if I used it with the routing config approach from react-router 6.4 it works fine

### LINKED ISSUE #330: How to make Signals work with Routes
Hi, does Signal not work with `Routes` from react-router-dom. 

I notice every time I include the import Signal statement (`import { useSignal } from '@preact/signals-react';`) in a component file where I use Routes. It will throw the error below:

```
Uncaught Error: [Route] is not a <Route> component. All component children of <Routes> must be a <Route> or <React.Fragment>
```

image

```
import React, { Suspense } from 'react';
import Box1 from './Box1';
import {
  Route, Navigate, Routes,
} from 'react-router-dom';

const SignalsPattern = () => (
       <Routes>
        <Route
          path='/procedure'
          element={(
            <Suspense fallback=''>
              <Box1 />
            </Suspense>
          )}
        />
      </Routes>
);
```

### PR DESCRIPTION
**Pull request by andrewiggins**
Revert our react integration back to setting up signal subscription tracking by watching changes in the ReactCurrentDispatcher instead of proxying function Component calls in createElement so it works with more ecosystem libraries such as react-router-dom.

Check the comment in the source for a deeper discussion of the implementation details and choices.

Fixes #251 
Fixes #330

### CODE REVIEW

File: packages/react/src/index.ts [hunk 1]
```diff
@@ -163,24 +103,138 @@ function createEffectStore() {
...
+		const isExitingComponentRender =
+			currentDispatcherType === ValidDispatcherType &&
+			nextDispatcherType === ContextOnlyDispatcherType;
+
+		// Update the current dispatcher now so the hooks inside of the
+		// useSyncExternalStore shim get the right dispatcher.
+		currentDispatcher = nextDispatcher;
+		if (isEnteringComponentRender) {
+			lock = true;
+			const storeRef = nextDispatcher.useRef<EffectStore>();
```
Comment (andrewiggins) [inline packages/react/src/index.ts:181]: Instead of using a weakmap or tracking ReactCurrentOwner, I'm just using a good 'ol ref to store our updater/store.

Note: ReactCurrentOwner is only used for class components in the production build of React so we can't use that anyway :/

**Comment by XantreGodlike** [comment]
This is really good job

File: packages/react/src/index.ts [hunk 2]
```diff
@@ -163,24 +103,138 @@ function createEffectStore() {
...
+			if (storeRef.current == null) {
+				storeRef.current = createEffectStore();
 			}
+
+			const store = storeRef.current;
+			useSyncExternalStore(
+				store.subscribe,
+				store.getSnapshot,
+				store.getSnapshot
+			);
```
Comment (andrewiggins) [inline packages/react/src/index.ts:191]: TODO: move these hook calls into a custom hook function for hopefully better grouping in devtools

**Review by JoviDeCroock — APPROVED** [review]

**Comment by ShivamJoker** [comment]
Hoping it fixes some of my issues as well.

**Comment by andrewiggins** [comment]
Gonna go ahead and merge this now. Happy to address any feedback afterwards though. Just @-mention in any comments :)

**Comment by salamaashoush** [comment]
@andrewiggins  Thanks a lot for fixing that issue :D
